Enable/fix Windows testing, enable Mac/Windows in Github Actions: Closes #335
pytest-dev/pytest-html pull request #337
Opened 2020-09-19 01:14 UTC by csm10495

Fix the default encoding by patching open to always use utf-8. This is the default on *nix based systems, though is different on Windows (and possibly others). 

Also while here, add testing for Mac/Windows to Github Actions

2020-09-28 00:08 UTC, csm10495 commented
@ssbarnea can you check this?

2020-09-28 09:17 UTC, ssbarnea requested changes
You must use different names for jobs in order to avoid confusions, example: "py3x-(windows|macos|linux)".

2020-10-12 02:21 UTC, csm10495 commented
@ssbarnea I finally got around to fixing this. Check it again. Right now it fails because of https://github.com/actions/setup-python/issues/151 (I don't think its my change specifically). 

Also in order to merge I think you may need to change settings to change the required actions for merge (since I changed the names):
![image](https://user-images.githubusercontent.com/5749838/95698474-e5313600-0bf6-11eb-8f01-e45f1d6a33b5.png)

2020-10-23 01:21 UTC, gnikonorov commented
Hey @csm10495 can you resolve merge conflicts, then I can take  a look

2020-10-23 01:21 UTC, csm10495 commented
Yep working on it and the commit rewrite.

2020-10-23 01:54 UTC, gnikonorov requested changes

2020-10-23 01:54 UTC, gnikonorov commented on pytest_html/extras.py
> -def extra(content, format, name=None, mime_type=None, extension=None):
I think the rebase is a little off. This change already exists in master ( see https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/extras.py#L13 ). It looks like this PR counts the merge of master as your changes

2020-10-23 01:57 UTC, csm10495 commented
Closing in favor of a new PR.

2020-10-23 01:57 UTC, closed without merging