Add ESLint to project
pytest-dev/pytest-html pull request #367
Opened 2020-11-11 06:10 UTC by gnikonorov

Add [ESLint](https://eslint.org/) for JS linting.

This better sets us up to tackle https://github.com/pytest-dev/pytest-html/issues/350, and should be added in as a best practice regardless.

The `.eslintrc.json` file was auto-generated by `ESLint`.

2020-11-11 06:20 UTC, gnikonorov commented
Note the `grunt` task is not actually run anymore. It's only showing because I didn't rename the action in my initial PR. It's an issue with GitHub actions and not the change

2020-11-11 08:17 UTC, ssbarnea requested changes
You missed the most important bit: adding eslint to .pre-commit-config.yaml so it runs during linting.

If you do this you do not need to alter any github actions.

2020-11-11 13:21 UTC, BeyondEvil requested changes
Almost every `var` can be changed to `const`. 

Add this rule: https://eslint.org/docs/rules/prefer-const

And it should help you out.

2020-11-11 13:21 UTC, BeyondEvil commented on pytest_html/resources/main.js
> +        var dataCell = elem.childNodes[1].childNodes[col_index].firstChild;
this should probably be `const`

2020-11-11 13:21 UTC, BeyondEvil commented on pytest_html/resources/main.js
> +        var icon = document.createElement('div');
`const`

2020-11-11 13:42 UTC, gnikonorov commented
> Almost every `var` can be changed to `const`. 
> 
> 
> 
> Add this rule: https://eslint.org/docs/rules/prefer-const
> 
> 
> 
> And it should help you out.

Let me take some time today and read over the rule list to see what else we may want to add

2020-11-12 01:54 UTC, gnikonorov commented
> You missed the most important bit: adding eslint to .pre-commit-config.yaml so it runs during linting.
> 
> If you do this you do not need to alter any github actions.

Good point @ssbarnea, thank you for pointing this out. I've updated the PR accordingly

2020-11-12 01:58 UTC, gnikonorov commented
@BeyondEvil @ssbarnea I've gone through the rule list and added every rule I thought made sense that didn't involve sweeping changes ( I'd feel safer adding those in a follow up PR to avoid breaking things ) except for the following sections:
- https://eslint.org/docs/rules/#stylistic-issues
- https://eslint.org/docs/rules/#ecmascript-6

From the rest of the rule list, I intentionally skipped the following rules since they involved making a refactor, which I want to address in a follow up PR to decrease the size of this one:
- https://eslint.org/docs/rules/no-use-before-define
- https://eslint.org/docs/rules/#strict-mode
- https://eslint.org/docs/rules/camelcase

If we are happy with this PR, I'd like to raise the above as separate issues after this merges so we don't forget about them and add them in time permitting.

2020-11-12 10:58 UTC, BeyondEvil approved these changes
LGTM! 🎉 

But let's wait for @ssbarnea before merging.

2020-11-12 12:26 UTC, ssbarnea approved these changes

2020-11-12 12:34 UTC, merged