Add codecov badge to readme
pytest-dev/pytest-html pull request #379
Opened 2020-11-25 00:05 UTC by gnikonorov

Add a coverage badge to the `README.rst` file now that we have codecov up. The link was recommended by codecov in the Settings -> Badge  section under 'RST'

2020-11-25 10:03 UTC, ssbarnea requested changes
We don't need more badges, it will break rendering on some screens by wrapping the badge line. Example: https://pypi.org/project/pytest-html/

2020-11-25 10:05 UTC, ssbarnea commented
PS. I could change my mind if we remove another one. I have nothing against coverage badge in particular, only about total number of badges. I hate to see wrapped badge lines, on github or pypi. 

PS. I use split screens, do not assume everyone uses landscape mode.

2020-11-25 13:54 UTC, gnikonorov commented
Sure. How about we remove the 'open issues' badge? I think it gives less value than a codecov badge since it just shows the same information as the issues tab.

2020-11-25 14:21 UTC, ssbarnea commented
It would not work in docs. For pypi luckly they display number of open issues on the left sidebar so we could remove it.
Mainly I am ok to swap issues with codecov, seams as acceptable trade-off.

2020-11-25 20:19 UTC, BeyondEvil reviewed
I'm fine with replacing open issues with codecov. 👍

2020-11-26 01:23 UTC, gnikonorov commented
Just removed the open issues badge, @ssbarnea and @BeyondEvil

2020-11-26 08:36 UTC, ssbarnea approved these changes

2020-11-26 08:36 UTC, merged