fix: Report fails to render with pytest-xdist
pytest-dev/pytest-html pull request #591
Opened 2023-03-10 14:40 UTC by BeyondEvil

The reason why the report fails to render when running with `pytest-xdist`, is that it adds a `node` attribute with a `WorkerController` object as its value.

This object is unserializable, so it fails when trying to convert the test data to JSON.

This is proposed solution 1.

2023-03-10 15:07 UTC, nicoddemus commented
> There's also the option of making the WorkerController class serializable upstream. Ping @nicoddemus

IMHO the WorkerController is an implementation detail and of little to no value to users, so I don't see an advantage in serializing it. :+1:

2023-03-10 15:13 UTC, nicoddemus commented
Possibly, but more investigation would be needed.

2023-03-10 15:15 UTC, BeyondEvil commented
> Possibly, but more investigation would be needed.

I think it's safe to keep it out of the report.

It wasn't part of the legacy report afaict. And if someone has a use case for having it, we can re-add it easily.

2023-03-11 20:48 UTC, RonnyPfannschmidt requested changes
this is lossy in the face of valid extensions, os i recommend against it

2023-03-19 17:57 UTC, BeyondEvil commented
Fixed by: https://github.com/pytest-dev/pytest-html/pull/598

2023-03-19 17:57 UTC, closed without merging